[package]
name = "benchmark_contacts_rust"
version = "0.1.0"
edition = "2018"

[dependencies]
actix-web = "4.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
diesel = { version = "2.0", features = ["postgres", "r2d2"] }
dotenv = "0.15"
uuid = { version = "1.0", features = ["v4"] }

[dependencies.actix-rt]
version = "2.5"
