version: '3.8'

services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: contacts
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  python_aiohttp:
    build: ./python_aiohttp
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      DATABASE_URL: postgres://user:password@db:5432/contacts

  benchmark_client:
    build:
      context: ./benchmark_client
    depends_on:
      - python_aiohttp

volumes:
  pgdata:
