version: '3.8'

services:
  python_db:
    image: postgres:16
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: contacts_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  python_aiohttp:
    build: ./python_aiohttp
    depends_on:
      - python_db
    environment:
      DATABASE_URL: postgres://user:password@python_db:5432/contacts_db

  benchmark_python:
    build: ./benchmark_client
    depends_on:
      - python_aiohttp
    command:
      [
        "./benchmark",
        "--base-url=http://python_aiohttp:8080",
        "--post-count=1000000",
        "--get-count=1000000",
        "--post-workers=500",
        "--get-workers=500"
      ]
