services:
  common_service_template: &common_service
    environment:
      DATABASE_URL: postgres://user:password@db:5432/contacts_db
    networks:
      - backend
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/contacts" ]
      interval: 10s
      retries: 5
      start_period: 10s
      timeout: 5s

  common_benchmark_tests_template: &common_benchmark_tests
    build: ./benchmark_tests
    networks:
      - backend

  common_benchmark_template: &common_benchmark
    build: ./benchmark_tests
    networks:
      - backend

  db:
    image: postgres:16
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: contacts_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - backend
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user"]
      interval: 5s
      timeout: 5s
      retries: 5

  python_aiohttp:
    <<: *common_service
    build: ./python_aiohttp

  benchmark_tests_python:
    <<: *common_benchmark_tests
    depends_on:
      python_aiohttp:
        condition: service_healthy
    environment:
      BASE_URL: http://python_aiohttp:8080

  benchmark_python:
    <<: *common_benchmark
    depends_on:
      python_aiohttp:
        condition: service_healthy
    environment:
      BASE_URL: http://python_aiohttp:8080

  go_fiber:
    build: ./go_fiber
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DATABASE_URL=postgres://user:password@db:5432/contacts_db
    ports:
      - "8080:8080"
    networks:
      - backend

  benchmark_go:
    build: ./benchmark_client
    depends_on:
      - go_fiber
    command:
      [
        "./benchmark",
        "--base-url=http://go_fiber:8080",
        "--post-count=10000",
        "--get-count=10000",
        "--post-workers=100",
        "--get-workers=100"
      ]
    networks:
      - backend

  php_slim:
    build: ./php_slim
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DATABASE_URL=postgres://user:password@db:5432/contacts_db
    ports:
      - "8080:8080"
    networks:
      - backend

  benchmark_php:
    build: ./benchmark_client
    depends_on:
      - php_slim
    command:
      [
        "./benchmark",
        "--base-url=http://php_slim:8080",
        "--post-count=10000",
        "--get-count=10000",
        "--post-workers=100",
        "--get-workers=100"
      ]
    networks:
      - backend

  java_spring:
    build: ./java_spring
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DATABASE_URL=postgres://user:password@db:5432/contacts_db
    ports:
      - "8080:8080"
    networks:
      - backend

  benchmark_java:
    build: ./benchmark_client
    depends_on:
      - java_spring
    command:
      [
        "./benchmark",
        "--base-url=http://java_spring:8080",
        "--post-count=10000",
        "--get-count=10000",
        "--post-workers=100",
        "--get-workers=100"
      ]
    networks:
      - backend

  rust_actix:
    build: ./rust_actix
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DATABASE_URL=postgres://user:password@db:5432/contacts_db
    networks:
      - backend
    ports:
      - "8080:8080"

  benchmark_rust:
    build: ./benchmark_client
    depends_on:
      - rust_actix
    command:
      [
        "./benchmark",
        "--base-url=http://rust_actix:8080",
        "--post-count=10000",
        "--get-count=10000",
        "--post-workers=100",
        "--get-workers=100"
      ]
    networks:
      - backend

  node_express:
    build: ./node_express
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DATABASE_URL=postgres://user:password@db:5432/contacts_db
    networks:
      - backend
    ports:
      - "8080:8080"

  benchmark_node:
    build: ./benchmark_client
    depends_on:
      - node_express
    command:
      [
        "./benchmark",
        "--base-url=http://node_express:8080",
        "--post-count=10000",
        "--get-count=10000",
        "--post-workers=100",
        "--get-workers=100"
      ]
    networks:
      - backend

networks:
  backend:
    driver: bridge

volumes:
  pgdata:
